### ISSUE TITLE
Mini Player doesn't open on Windows 10

### ISSUE THREAD

**Issue by clarrence** [themagiulio/bandcamp-desktop#8]
I get the following :

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\User.Name\AppData\Local\Programs\bandcamp-desktop\resources\app.asar\main.js:129:42)
    at Request.self.callback (C:\Users\User.Name\AppData\Local\Programs\bandcamp-desktop\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (C:\Users\User.Name\AppData\Local\Programs\bandcamp-desktop\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (C:\Users\User.Name\AppData\Local\Programs\bandcamp-desktop\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[OK]

### **Thanks for making this btw!!**

**Comment by themagiulio** [comment]
Hi,
thanks for reporting that!
I think you tried to open the mini player on a page which doesn't contain an album, an ep or what else...

For instance, if I want to keep listening an album while I explore the website I need to go to the album page and open the Mini Player there.
I know this is not the perfect solution, but I'll try to improve it in the future :)
